server:
  port: 8090

spring:
  application:
    name: gateway-service

---
eureka:
  client:
    fetch-registry : true
    register-with-eureka : true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: UserFilter
              args:
                baseMessage: Spring Cloud Gateway UserFilter
                preLogger: true
                postLogger: true
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - name: CustomerFilter
              args:
                baseMessage: Spring Cloud Gateway CustomerFilter
                preLogger: true
                postLogger: true
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: OrderFilter
              args:
                baseMessage: Spring Cloud Gateway OrderFilter
                preLogger: true
                postLogger: true
        - id: sktservice-service
          uri: lb://SKTSERVICE-SERVICE
          predicates:
            - Path=/sktservice/**
          filters:
            - name: SktserviceFilter
              args:
                baseMessage: Spring Cloud Gateway SktserviceFilter
                preLogger: true
                postLogger: true
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: ProductFilter
              args:
                baseMessage: Spring Cloud Gateway ProductFilter
                preLogger: true
                postLogger: true